version: '3'

networks:
  educk-network:
    driver: bridge
    ipam:
      driver: default

services:
  educk-nginx:
    container_name: educk-nginx
    image: nginx
    ports:
      - '8080:80'
    links:
      - educk
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - educk-network


  educk:
    container_name: educk
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    image: educk
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
    networks:
      - educk-network
